spring:
  datasource:
    url: jdbc:postgresql://213.159.209.245:32770/test_database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        instance:
          metadata:
            tags:
              environment: local
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

