spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  application:
    admin:
      enabled: true
    name: fox-back
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/fox
          jwk-set-uri: http://localhost:8083/auth/realms/fox/protocol/openid-connect/certs
  boot:
    admin:
      client:
        url: http://localhost:${server.port}/admin
        instance:
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
      context-path: admin
      ui:
        available-languages: en

  jmx:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default-schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true

      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    liquibase:
      enabled: false

logging:
#  level:
  file:
    path: logs/spring-boot-application.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
server:
  port: 8081
rusgolf:
  host: http://hcp.rusgolf.ru/public/player/ru/?page=
sms-ru:
  url: https://sms.ru/sms
  api-id: 992A198F-8AA5-0DEB-C2DD-1D423A9F4350
  test: true
  timeout: 120  # in seconds

jwt:
  secret: c92c05b9-9b18-492e-80d6-f34b5122983e

